readme.md
It's fanfiction. Not a book. Not judging.
=> Edit HPMOR link

readme.md
I also corrected a typo. Would you be interested in bigger 'cleanup' PRs - the fact everything's in lower-case is kinda jarring, but I didn't wanna make massive corrections that wouldn't get accepted.
=> Adding some more resources on C, D, algorithms

readme.md
Added [Unsong](https://www.goodreads.com/book/show/28589297-unsong) and [The Metamorphosis of Prime Intellect](https://www.goodreads.com/book/show/64341.The_Metamorphosis_of_Prime_Intellect).
=> Added two fiction books

readme.md
Free ebook to learn React by building an own application: released 11 months ago, for free, downloaded by over 14.000 people, 200 pages. Maybe it helps people who favor a book over a course to get started in React.
=> Free React Book

readme.md
I'm not sure why it suggests that I've changed the License section
=> Add book to JavaScript section

README.md
@nikitavoloboev I have added **The Lean Startup(2011)** in **Bussiness** section. Please have a look.
=> The Lean Startup added in bussiness section

README.md
Written by a psychologist with a nobel prize in economics, this is a great intro to psychology.
=> Add book to psychology section

README.md
This PR adds the following books:
1. Hit Refresh 
2. Becoming
3. The Everything Store
=> Add biographies and autobiographies

README.md
Hi,
I was just going through the repo and I found a misspelled word at the Readme section, u can check out the changed files to learn more. 
In essence, I decided to correct it 😄.
Hope you had/you are having a nice day. 👍
=> Correct misspelt word.

README.md
Hi,
I thought this book might be a good contribution to the list.
Thanks for taking it into consideration!
=> Added API Design Patterns to the list

README.md
Hi,
This early-access book on cryptography might be a good match for the list.
Thanks again for your consideration!
Branko
=> Added Real World Cryptography to the list

README.md
Hi,
I thought this title might be a good contribution to the list.
Thanks for considering it!
Branko
=> Added Micro Frontends in Action to the list

README.md
Hello,
Thanks a lot for maintain this resources repo. I thought that my new book would be a valuable addition to your list of books.
Thanks for your consideration.
=> Add how machine learning works book

README.md
Hi,
I thought this book might be a good contribution.
Thanks for your consideration!
Branko
=> Added Designing APIs with Swagger and OpenAPI

README.md
Hi, I thought that `Learn PowerShell in a Month of Lunches, Linux and macOS Edition` might be great addition to your list of books. 
Thank you for your consideration
=> Add new PowerShell book

README.md
Hi, I proposed adding my new book Fighting Churn With Data.  It is a hands on course in applied data science in Python and SQL, taught through the use case of customer churn. -carl24K
=> Add book, Fighting Churn With Data

README.md
=> Add to clojure

README.md
Good for people like me who suffer from not keeping up with the development of C++ (or having read the wrong books).
=> add Stroustrup's "A Tour of C++"

README.md
_Practices of the Python Pro_ explores software design practices using Python as the scaffolding for examples.
Disclosure: this is my book, so I appreciate your consideration! I understand if self-submissions feel untrue to the nature of this wonderful list 👍
=> Add Practices of the Python Pro

README.md
Hi!
I have added the book "JavaScript: The Good Parts: The Good Parts" by Crockford. In addition, I have sorted the JavaScript books by date and fixed some emoji that were in the wrong encoding.
Have a nice week-end,
Martin
=> JavaScript: The Good Parts

README.md
Add MLwithTensorFlow2ed. Thanks for your consideration!
=> Add MLwithTensorFlow2ed

README.md
Hi,
I am Branko from Manning and I thought this book would be a good addition to the list.
Thanks for considering it!
=> Added Getting Started with Kubernetes 

readme.md
Hi,
I have added links to my web versions of the ebooks on Python, JavaScript and Ruby regular expressions.
=> Added regexp books for Python, JavaScript, Ruby

readme.md
Hi,
This PR has a lot of changes:
* changed `http` to `https` for goodreads links
* removed extra line 'The Best Interface Is No Interface' which was placed after the resource links (including this book)
* replaced amazon ref links with corresponding goodreads link
* resources added:
* Modern C
* Think Python
* linux-insides
* My books on GNU grep/sed/awk
=> http to https, removed referral links, added resources

readme.md
Added The Software Craftsman: Professionalism, Pragmatism, Pride by Sandro Mancuso (2014)
=> Added The Software Craftsman: Professionalism, Pragmatism, Pride

readme.md
Hello, I'm currently reading this book from [Dan Vanderkam](https://github.com/danvk) to learn advanced Typescript, and I think this might be a good addition to this list of books.
Thanks for considering.
=> Added a new book: Effective TypeScript: 62 Specific Ways to Improve Your Typescript

readme.md
Computer Graphics from Scratch demystifies the algorithms used in modern graphics software with basic programming and high school math.
=> added computer graphics from scratch

readme.md
Hi, I thought this title might be a great addition to your list of books. Thank you for your consideration.
=> Added Trust in Machine Learning

readme.md
Added Security Engineering as well as many philosophy such as tao of seneca, atlas shrugged as well as the subtle art of not giving a f*ck
=> Added security engineering and philosophy books

readme.md
Hi,
I am Stjepan from Manning Publications. I thought this title might be a good match for your list. Thank you for considering it.
Best,
=> Added Software Mistakes and Tradeoffs

readme.md
Hi,
Stjepan from Manning here. I thought this title might be a good match to your list. Thank you for considering it.
Best,
=> Added Securing Kubernetes Secrets

readme.md
Hi,
Stjepan from Manning here. I thought this title might be a good match to your list. Thank you for considering it.
Best,
=> Added Kubeflow in Action

readme.md
Hi,
Stjepan from Manning here. I thought this title might be a good match for your list. Thank you for considering it.
Best,
=> Added Parallel an High-Performance Computing

readme.md
Hi,
Stjepan from Manning here. I thought this title might be a good match for your list. Thank you for considering it.
Best,
=> Added The Programmer's Brain

readme.md
HI,
Stjepan from Manning here. I've fixed one of the links that weren't working. Please, update.
=> Fixed the wrong link

readme.md
Hi,
Stjepan from Manning here. I thought this title might be a good match for your Go list. Thank you for considering it.
Best,
=> Added Learn Concurrent Programming with Go

readme.md
Hey there,
I just released a book about TypeScript, and it would be such an honor for me if you could publish the link to my book on your repository. Thank you so much for considering my request, and keep up the fantastic work!
=> Update book about TypScript

readme.md
The entry already exists in line 1002
=> Remove duplicate "API Design Patterns" entry

readme.md
Added Elements of Kotlin and Fundamentals of Psychological Disorders
=> Added Kotlin and Psychology books to readme.md
